version: "3.0"
services:
  agent-grabber:
    build: ./agent-grabber
    volumes:
      - "bookstore-agent-volume:/agents"
  bookstore-datamanager:
    build: ./bookstore-data-manager
    depends_on:
      - agent-grabber
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/mvn"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast-java
      - ./env-wait-for-then-exec

    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Data Manager"
  bookstore-devservice:
    build: ./bookstore-devservice
    depends_on:
      - agent-grabber
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/java"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast-java
      - ./env-wait-for-then-exec
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Devservice"
  bookstore-frontend:
    build: ./bookstore-frontend
    depends_on:
      - agent-grabber
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/mvn"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast-java
      - ./env-wait-for-then-exec
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Front End"
      - "JAVA_TOOL_OPTIONS=-Djavax.xml.accessExternalDTD=all -javaagent:/agents/java/contrast.jar"
  bookstore-profanity-checker:
    build: ./bookstore-profanity-checker
    depends_on:
      - agent-grabber
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/mvn"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast-java
      - ./env-wait-for-then-exec
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Profanity Checker"
volumes:
  bookstore-agent-volume:
