# Note: this file should always be used in conjunction with docker-compose.yml
# For example:
#   docker-compose -f docker-compose.yml -f docker-compose-contrast.yml up
version: "3.0"
services:
  agent-grabber:
    build:
      context: ./agent-grabber
      dockerfile: ./Dockerfile
      args:
        - URL=${URL}
        - API_KEY=${API_KEY}
        - ORG_ID=${ORG_ID}
        - AUTH_HDR=${AUTH_HDR}
    volumes:
      - "./contrast_security-user.yaml:/app/contrast_security-user.yaml"
      - "bookstore-agent-volume:/agents"
  bookstore-datamanager:
    build: ./bookstore-data-manager
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/mvn"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast/java-common-env
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Data Manager"
  bookstore-devservice:
    build: ./bookstore-devservice
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/java"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast/java-common-env
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Devservice"
  bookstore-frontend:
    build: ./bookstore-frontend
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/mvn"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast/java-common-env
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Front End"
      - "JAVA_TOOL_OPTIONS=-Djavax.xml.accessExternalDTD=all -javaagent:/agents/java/contrast.jar"
  bookstore-profanity-checker:
    build: ./bookstore-profanity-checker
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./wait-for-then-exec.sh:/app/mvn"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast/java-common-env
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Profanity Checker"
  bookstore-favorites:
    volumes:
      - "./contrast_security.yaml:/app/contrast_security.yaml"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast/node-common-env
    environment:
      - "WAIT_FOR=bookstore-mongodb:27017 contrast-agent:node"
      - "CONTRAST__APPLICATION__NAME=Bookstore Favorites"
  bookstore-reviews:
    volumes:
      - "./contrast_security.yaml:/app/contrast_security.yaml"
      - "bookstore-agent-volume:/agents"
    env_file:
      - ./env-contrast/python-common-env
    environment:
      - "WAIT_FOR=bookstore-mongodb:27017 contrast-agent:python"
      - "CONTRAST__APPLICATION__NAME=Bookstore Reviews"
      
volumes:
  bookstore-agent-volume:
